(********************************************************************
	@name Stdlib.declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Stdlib.transformation.
 ********************************************************************)
		 
 From Stdlib Require Import List.
 Require Import core.Model.
 From Stdlib Require Import String.
 Require Import transformations.Moore2Mealy.Mealy.
 Open Scope string_scope.
 
(* Moore models as counterexample to prove injectivity of  CoqTL *)

 
Definition Mealy_model : Model Mealy.MM :=
(Build_Model Mealy.MM
    (
        (State (Build_State_t  (Id.Id "S2"))) :: nil
    )
    ( nil )
).


