(********************************************************************
	@name Coq declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
 Require Import List.
 Require Import core.Model.
 Require Import String.
 Require Import transformations.Moore2Mealy.Moore.
 Open Scope string_scope.
 
(* Moore models as counterexample to prove distributivity of CoqTL *)

 

Definition Moore_m1 : Model Moore.MM :=
    (Build_Model Moore.MM
       (
        (TransitionElement (Build_Transition_t 0 "0")) :: 
        (TransitionElement (Build_Transition_t 1 "1")) :: nil
       )
       (
           nil
       )
    ).

Definition Moore_m2 : Model Moore.MM :=
       (Build_Model Moore.MM
           (
               (StateElement (Build_State_t  "S0" "1")) :: 
               (StateElement (Build_State_t  "S1" "0")) ::  
               nil
           )
           (
               (Transition_sourceLink (Build_Transition_source_t (Build_Transition_t 0 "0") (Build_State_t  "S1" "0"))) ::
               (Transition_targetLink (Build_Transition_target_t (Build_Transition_t 0 "0") (Build_State_t  "S0" "1"))) ::
               (Transition_sourceLink (Build_Transition_source_t (Build_Transition_t 1 "1") (Build_State_t  "S0" "1"))) ::
               (Transition_targetLink (Build_Transition_target_t (Build_Transition_t 1 "1") (Build_State_t  "S1" "0"))) ::
               nil
           )
       ).
