(********************************************************************
	@name Coq declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Moore2Mealy.Moore.
Open Scope string_scope.
Import Glue. 

(* Moore models as counterexample to prove distributivity of CoqTL *)

 

Definition Moore_m1 : Model Moore.MM :=
    (Build_Model Moore.MM
       (
        (Transition (Build_Transition_t 0 "0")) :: 
        (Transition (Build_Transition_t 1 "1")) :: nil
       )
       (
           nil
       )
    ).

Definition Moore_m2 : Model Moore.MM :=
       (Build_Model Moore.MM
           (
               (State (Build_State_t  (Id.Id "S0") "1")) :: 
               (State (Build_State_t  (Id.Id "S1") "0")) ::  
               nil
           )
           (
               (TransitionSource (Build_Glue _ _ (Build_Transition_t 0 "0") (Build_State_t  (Id.Id "S1") "0"))) ::
               (TransitionTarget (Build_Glue _ _ (Build_Transition_t 0 "0") (Build_State_t  (Id.Id "S0") "1"))) ::
               (TransitionSource (Build_Glue _ _ (Build_Transition_t 1 "1") (Build_State_t  (Id.Id "S0") "1"))) ::
               (TransitionTarget (Build_Glue _ _ (Build_Transition_t 1 "1") (Build_State_t  (Id.Id "S1") "0"))) ::
               nil
           )
       ).
