
#Fix generated html files.
COQDOCEXTRAFLAGS=--toc-depth 8 --toc --no-lib-name --lib-subtitles --multi-index

COQEXTRAFLAGS=-w -intuition-auto-with-star

M2MPROOFS= transformations/Moore2Mealy/theorems/SemanticsPreservation.vo

M2MTESTS= transformations/Moore2Mealy/tests/sampleMooreTest.vo

C2RPROOFS= transformations/Class2Relational/theorems/All_classes_instantiate_impl.vo\
	   transformations/Class2Relational/theorems/All_classes_match_impl.vo\
	   transformations/Class2Relational/theorems/Attribute_name_preservation.vo\
	   transformations/Class2Relational/theorems/C2R_monotonicity.vo\
	   transformations/Class2Relational/theorems/Column_name_uniqueness.vo\
	   transformations/Class2Relational/theorems/Elements.vo\
	   transformations/Class2Relational/theorems/Relational_name_definedness_spec.vo\
	   transformations/Class2Relational/theorems/Relational_resolve_spec.vo\
	   transformations/Class2Relational/theorems/Relational_resolve.vo\
	   transformations/Class2Relational/theorems/Table_name_uniqueness.vo

C2RTESTS= transformations/Class2Relational/tests/PersonTest.vo

PAIRPROOFS= transformations/Class2Relational_TUPLES/theorems/Attribute_name_preservation.vo\
	    transformations/Class2Relational_TUPLES/theorems/Column_name_uniqueness.vo\
	    transformations/Class2Relational_TUPLES/theorems/Elements.vo\
	    transformations/Class2Relational_TUPLES/theorems/Relational_name_definedness_spec.vo\
	    transformations/Class2Relational_TUPLES/theorems/Table_name_uniqueness.vo

TACTICTESTS= test_tactics/TestTacticsBW.vo\
	     test_tactics/TestTacticsFW.vo\
	     test_tactics/TestUtils.vo\
	     test_tactics/TestChoiceTools.vo\
	     test_tactics/TestConcreteExpressionTools.vo


proofs: $(M2MPROOFS) $(C2RPROOFS) $(PAIRPROOFS)

clean_tests:
	rm -f $(M2MTESTS) $(C2RTESTS) $(TACTICTESTS)

transformation_tests: $(M2MTESTS) $(C2RTESTS) 

tactic_tests: $(TACTICTESTS)

metrics:
	@echo "Metrics for the provided lammas and tactics:"
	@coqwc usertools/*.v
	@echo "Metrics for Moore2Mealy:"
	@coqwc transformations/Moore2Mealy/*.v transformations/Moore2Mealy/*/*.v
	@echo "Metrics for Class2Relational:"
	@coqwc transformations/Class2Relational/*.v transformations/Class2Relational/*/*.v

grep_tactics:
	find transformations -name "*.v" -exec grep in_compute_trace_inv_singleton_fw \{\} \; -print
	find transformations -name "*.v" -exec grep transform_link_fw_tac_singleton \{\} \; -print
	find transformations -name "*.v" -exec grep in_modelElements_singleton_fw_tac \{\} \; -print
	find transformations/Class2Relational -name "*.v" -exec grep exploit_in_trace \{\} \; -print
	find transformations -name "*.v" -exec grep exploit_link_in_result \{\} \; -print
	find transformations -name "*.v" -exec grep exploit_element_in_result \{\} \; -print

