(********************************************************************
	@name Coq declarations for model
	@date 2021/11/22 10:09:58
	@description Automatically generated by XMI2Coq transformation.
        MODIFIED BY HAND
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Families2Persons.Families.
Open Scope string_scope.

Import Glue.

Definition InputModel : Families.M :=
	(Build_Model Families.MM
		(
		(MemberElement (Build_Member_t  "David")) :: 
		(MemberElement (Build_Member_t  "Kelly")) :: 
		(MemberElement (Build_Member_t  "Peter")) :: 
		(MemberElement (Build_Member_t  "Jim")) :: 
		(MemberElement (Build_Member_t  "Dylan")) :: 
		(FamilyElement (Build_Family_t  "March")) :: 
		(MemberElement (Build_Member_t  "Brenda")) :: 
		(MemberElement (Build_Member_t  "Cindy")) :: 
		(MemberElement (Build_Member_t  "Jackie")) :: 
		(MemberElement (Build_Member_t  "Brandon")) :: 
		(FamilyElement (Build_Family_t  "Sailor")) :: 
		nil)
		(
		(Member_familySonLink (glue (Build_Member_t  "David") with (Build_Family_t  "Sailor"))) ::
		(Member_familyDaughterLink (glue (Build_Member_t  "Kelly") with (Build_Family_t  "Sailor"))) ::
		(Member_familyFatherLink (glue (Build_Member_t  "Peter") with (Build_Family_t  "Sailor"))) ::
		(Member_familyFatherLink (glue (Build_Member_t  "Jim") with (Build_Family_t  "March"))) ::
		(Member_familySonLink (glue (Build_Member_t  "Dylan") with (Build_Family_t  "Sailor"))) ::
		(Family_ffatherLink (glue (Build_Family_t  "March") with (Build_Member_t  "Jim"))) ::
		(Family_fmotherLink (glue (Build_Family_t  "March") with (Build_Member_t  "Cindy"))) ::
		(Family_fsonsLink (glue (Build_Family_t  "March") with ((Build_Member_t  "Brandon") :: nil ))) ::
		(Family_fdaughtersLink (glue (Build_Family_t  "March") with ((Build_Member_t  "Brenda") :: nil ))) ::
		(Member_familyDaughterLink (glue (Build_Member_t  "Brenda") with (Build_Family_t  "March"))) ::
		(Member_familyMotherLink (glue (Build_Member_t  "Cindy") with (Build_Family_t  "March"))) ::
		(Member_familyMotherLink (glue (Build_Member_t  "Jackie") with (Build_Family_t  "Sailor"))) ::
		(Member_familySonLink (glue (Build_Member_t  "Brandon") with (Build_Family_t  "March"))) ::
		(Family_ffatherLink (glue (Build_Family_t  "Sailor") with (Build_Member_t  "Peter"))) ::
		(Family_fmotherLink (glue (Build_Family_t  "Sailor") with (Build_Member_t  "Jackie"))) ::
		(Family_fsonsLink (glue (Build_Family_t  "Sailor") with ((Build_Member_t  "David") :: (Build_Member_t  "Dylan") :: nil ))) ::
		(Family_fdaughtersLink (glue (Build_Family_t  "Sailor") with ((Build_Member_t  "Kelly") :: nil ))) ::
		nil)
	).
