(********************************************************************
	@name Coq declarations for model
	@date 2021/11/22 10:09:58
	@description Automatically generated by XMI2Coq transformation.
        MODIFIED BY HAND
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Families2Persons.Families.
Open Scope string_scope.


Definition InputModel : Families.M :=
	(Build_Model Families.MM
		(
		(MemberElement (Build_Member_t  "David")) :: 
		(MemberElement (Build_Member_t  "Kelly")) :: 
		(MemberElement (Build_Member_t  "Peter")) :: 
		(MemberElement (Build_Member_t  "Jim")) :: 
		(MemberElement (Build_Member_t  "Dylan")) :: 
		(FamilyElement (Build_Family_t  "March")) :: 
		(MemberElement (Build_Member_t  "Brenda")) :: 
		(MemberElement (Build_Member_t  "Cindy")) :: 
		(MemberElement (Build_Member_t  "Jackie")) :: 
		(MemberElement (Build_Member_t  "Brandon")) :: 
		(FamilyElement (Build_Family_t  "Sailor")) :: 
		nil)
		(
		(Member_familySonLink (Build_Member_familySon_t (Build_Member_t  "David") (Build_Family_t  "Sailor"))) ::
		(Member_familyDaughterLink (Build_Member_familyDaughter_t (Build_Member_t  "Kelly") (Build_Family_t  "Sailor"))) ::
		(Member_familyFatherLink (Build_Member_familyFather_t (Build_Member_t  "Peter") (Build_Family_t  "Sailor"))) ::
		(Member_familyFatherLink (Build_Member_familyFather_t (Build_Member_t  "Jim") (Build_Family_t  "March"))) ::
		(Member_familySonLink (Build_Member_familySon_t (Build_Member_t  "Dylan") (Build_Family_t  "Sailor"))) ::
		(Family_ffatherLink (Build_Family_ffather_t (Build_Family_t  "March") (Build_Member_t  "Jim"))) ::
		(Family_fmotherLink (Build_Family_fmother_t (Build_Family_t  "March") (Build_Member_t  "Cindy"))) ::
		(Family_fsonsLink (Build_Family_fsons_t (Build_Family_t  "March") ((Build_Member_t  "Brandon") :: nil ))) ::
		(Family_fdaughtersLink (Build_Family_fdaughters_t (Build_Family_t  "March") ((Build_Member_t  "Brenda") :: nil ))) ::
		(Member_familyDaughterLink (Build_Member_familyDaughter_t (Build_Member_t  "Brenda") (Build_Family_t  "March"))) ::
		(Member_familyMotherLink (Build_Member_familyMother_t (Build_Member_t  "Cindy") (Build_Family_t  "March"))) ::
		(Member_familyMotherLink (Build_Member_familyMother_t (Build_Member_t  "Jackie") (Build_Family_t  "Sailor"))) ::
		(Member_familySonLink (Build_Member_familySon_t (Build_Member_t  "Brandon") (Build_Family_t  "March"))) ::
		(Family_ffatherLink (Build_Family_ffather_t (Build_Family_t  "Sailor") (Build_Member_t  "Peter"))) ::
		(Family_fmotherLink (Build_Family_fmother_t (Build_Family_t  "Sailor") (Build_Member_t  "Jackie"))) ::
		(Family_fsonsLink (Build_Family_fsons_t (Build_Family_t  "Sailor") ((Build_Member_t  "David") :: (Build_Member_t  "Dylan") :: nil ))) ::
		(Family_fdaughtersLink (Build_Family_fdaughters_t (Build_Family_t  "Sailor") ((Build_Member_t  "Kelly") :: nil ))) ::
		nil)
	).
