(********************************************************************
	@name Coq declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Moore2Mealy.Moore.
Open Scope string_scope.

(* S0("1") --"1"-> S1("0")  
	 	   <-"0"--
	*)

Definition InputModel : Model MooreMetamodel_Metamodel_Instance :=
	(Build_Model MooreMetamodel_Metamodel_Instance
		(
		(Build_MooreMetamodel_Object Transition_K (BuildTransition  "0")) :: 
		(Build_MooreMetamodel_Object State_K (BuildState  "S0" "1")) :: 
		(Build_MooreMetamodel_Object State_K (BuildState  "S1" "0")) :: 
		(Build_MooreMetamodel_Object Transition_K (BuildTransition  "1")) :: 
		nil)
		(
		(Build_MooreMetamodel_Link TransitionSource_K (BuildTransitionSource (BuildTransition  "0") (BuildState  "S1" "0"))) ::
		(Build_MooreMetamodel_Link TransitionTarget_K (BuildTransitionTarget (BuildTransition  "0") (BuildState  "S0" "1"))) ::
		(Build_MooreMetamodel_Link TransitionSource_K (BuildTransitionSource (BuildTransition  "1") (BuildState  "S0" "1"))) ::
		(Build_MooreMetamodel_Link TransitionTarget_K (BuildTransitionTarget (BuildTransition  "1") (BuildState  "S1" "0"))) ::
		nil)
	).
