(********************************************************************
	@name Coq declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Moore2Mealy.Moore.
Open Scope string_scope.

(* S0("1") --"1"-> S1("0")  
	 	   <-"0"--
	*)

Definition InputModel : Model MooreMM :=
	(Build_Model MooreMM
		(
		(TransitionElement (BuildTransition  "0")) :: 
		(StateElement (BuildState  "S0" "1")) :: 
		(StateElement (BuildState  "S1" "0")) :: 
		(TransitionElement (BuildTransition  "1")) :: 
		nil)
		(
		(Transition_sourceLink (BuildTransitionSource (BuildTransition  "0") (BuildState  "S1" "0"))) ::
		(Transition_targetLink (BuildTransitionTarget (BuildTransition  "0") (BuildState  "S0" "1"))) ::
		(Transition_sourceLink (BuildTransitionSource (BuildTransition  "1") (BuildState  "S0" "1"))) ::
		(Transition_targetLink (BuildTransitionTarget (BuildTransition  "1") (BuildState  "S1" "0"))) ::
		nil)
	).
