(********************************************************************
	@name Coq declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Moore2MealyALT.Moore.
Open Scope string_scope.

Import Id.

(* S0("1") --"1"-> S1("0")  
	 	   <-"0"--
	*)

Definition id0 := Id "S0".
Definition id1 := Id "S1".

Definition InputModel : Model Moore.MM :=
  let t0 := Build_Transition_t id0 "0" id1 in 
  let t1 := Build_Transition_t id1 "1" id1 in
  let s0 := Build_State_t id0 "1" in
  let s1 := Build_State_t id1 "0" in
  Build_Model Moore.MM
    (
      (TransitionElement t0) :: 
	(StateElement s0) :: 
	(StateElement s1) :: 
	(TransitionElement t1) :: 
	nil
    )
    (	nil
    )
.
