(********************************************************************
	@name Coq declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
Require Import List.
Require Import core.Model.
Require Import String.
Require Import transformations.Moore2MealyALT.Moore.
Open Scope string_scope.

(* S0("1") --"1"-> S1("0")  
	 	   <-"0"--
	*)

Definition InputModel : Model Moore.MM :=
  let t0 := Build_Transition_t 0 "0" in 
  let t1 := Build_Transition_t 1 "1" in
  let s0 := Build_State_t "S0" "1" in
  let s1 := Build_State_t "S1" "0" in
  Build_Model Moore.MM
    (
      (TransitionElement t0) :: 
	(StateElement s0) :: 
	(StateElement s1) :: 
	(TransitionElement t1) :: 
	nil
    )
    (
      (Transition_sourceLink (Build_Transition_source_t t0 s1)) ::
	(Transition_targetLink (Build_Transition_target_t t0 s0)) ::
	(Transition_sourceLink (Build_Transition_source_t t1 s0)) ::
	(Transition_targetLink (Build_Transition_target_t t1 s1)) ::
	nil
    )
.
