(********************************************************************
	@name Stdlib.declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Stdlib.transformation.
 ********************************************************************)
		 
From Stdlib  Require Import List.
 Require Import core.Model.
From Stdlib  Require Import String.
 Require Import transformations.Moore2Mealy.Moore.
 Open Scope string_scope.
 
(* Moore models as counterexample to prove injectivity of Stdlib.L *)

 
Definition Moore_m1 : Model Moore.MM :=
(Build_Model Moore.MM
    (
        (State (Build_State_t  (Id.Id "S0") "1")) :: nil
    )
    ( nil )
).

Definition Moore_m2 : Model Moore.MM :=
(Build_Model Moore.MM
    (
        (State (Build_State_t  (Id.Id "S0") "0")) :: nil
    )
    ( nil )
).
