(********************************************************************
	@name Coq declarations for model
	@date 2022/01/29 15:46:30
	@description Automatically generated by XMI2Coq transformation.
 ********************************************************************)
		 
 Require Import List.
 Require Import core.Model.
 Require Import String.
 Require Import transformations.Moore2Mealy.Moore.
 Open Scope string_scope.
 
(* Moore models as counterexample to prove injectivity of CoqTL *)

 
Definition Moore_m1 : Model Moore.MM :=
(Build_Model Moore.MM
    (
        (StateElement (Build_State_t  "S0" "1")) :: nil
    )
    ( nil )
).

Definition Moore_m2 : Model Moore.MM :=
(Build_Model Moore.MM
    (
        (StateElement (Build_State_t  "S0" "0")) :: nil
    )
    ( nil )
).
